language: go
go:
- 1.4
before_install:
- go get github.com/onsi/ginkgo/...
- go get github.com/onsi/gomega/...
- go install github.com/onsi/ginkgo/ginkgo
- bin/install
script: PATH=$PATH:$HOME/gopath/bin ginkgo -r .
branches:
  only:
  - master
